{% set version = "12.6.0" %}

package:
  name: cuda-libraries-static
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart-static 12.6.37
    - cuda-nvrtc-static 12.6.20
    - libcublas-static 12.6.0.22      # [linux]
    - libcufft-static 11.2.6.28      # [linux]
    - libcufile-static 1.11.0.15       # [linux]
    - libcurand-static 10.3.7.37    # [linux]
    - libcusolver-static 11.6.4.38  # [linux]
    - libcusparse-static 12.5.2.23  # [linux]
    - libnpp-static 12.3.1.23         # [linux]
    - libnvfatbin-static 12.6.20
    - libnvjitlink-static 12.6.20
    - libnvjpeg-static 12.3.3.23     # [linux]

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library static packages.
  description: |
    Meta-package containing all available library static packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
