{% set version = "12.0.0" %}

package:
  name: cuda-libraries-static
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 2
  noarch: generic

requirements:
  run:
    - __linux               # [linux]
    - __win                 # [win]
    - __archspec * x86_64   # [x86_64]
    - __archspec * aarch64  # [aarch64]
    - __archspec * ppc64le  # [ppc64le]
    - cuda-cudart-static 12.0.107
    - cuda-nvrtc-static 12.0.76
    - libcublas-static 12.0.1.189
    - libcufft-static 11.0.0.21
    - libcufile-static 1.5.0.59  # [linux64]
    - libcurand-static 10.3.1.50
    - libcusolver-static 11.4.2.57
    - libcusparse-static 12.0.0.76
    - libnpp-static 12.0.0.30
    - libnvjitlink-static 12.0.76
    - libnvjpeg-static 12.0.0.28

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library static packages.
  description: |
    Meta-package containing all available library static packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - adibbley
